[[recipes]]
id = "poulet_arc_en_ciel"
title = "Poulet arc-en-ciel ğŸ“ğŸŒˆ"
subtitle = "Des couleurs et du goÃ»t ğŸ˜‹"
video = "https://www.facebook.com/chefclublightandfun/videos/353013945166903/"
recipecard = "http://res.cloudinary.com/dil9tlpjt/image/upload/v1521482471/012518_ROULE_POULET_LF_ezlfwv.jpg"

[[recipes]]
id = "quiche_patate_douce"
title = "La quiche patate douce ğŸ "
subtitle = "Un rÃ©gime Ã  la douce ğŸ˜Š"
video = "https://www.facebook.com/chefclublightandfun/videos/358379331297031/"
recipecard = "http://res.cloudinary.com/dil9tlpjt/image/upload/v1521482716/011018_QUICHE_PATATE_DOUCE_LF_ceej3f.jpg"

[[recipes]]
id = "mousse_chocolat_bi_gout"
title = "La mousse au chocolat bi-goÃ»t ğŸ«"
subtitle = "Onctueux et trÃ¨s peu calorique :)"
video = "https://www.facebook.com/chefclublightandfun/videos/365741530560811/"
recipecard = "http://res.cloudinary.com/dil9tlpjt/image/upload/v1521483006/022318_MOUSSE_CHOCOLAT_EAU_LF_ix9tgg.jpg"

[[recipes]]
id = "terrine_petits_legumes"
title = "Terrine aux petits lÃ©gumes ğŸ¥¦ğŸ¥•ğŸ†"
subtitle = "Aussi lÃ©gÃ¨re que colorÃ©e"
video = "https://www.facebook.com/chefclublightandfun/videos/366697307131900/"
recipecard = "http://res.cloudinary.com/dil9tlpjt/image/upload/v1521483050/020618_TERRINE_TROIS_LEGUMES_LF_fsf7vz.jpg"

[[recipes]]
id = "chou_fleur_margherita"
title = "Chou-fleur faÃ§on margherita ğŸ•"
subtitle = "Tous les bons cÃ´tÃ©s de la pizza en plus lÃ©ger :)"
video = "https://www.facebook.com/chefclublightandfun/videos/369213040213660/"
recipecard = "http://res.cloudinary.com/dil9tlpjt/image/upload/v1521483076/011118_PIZZA_CHOUFLEUR_LF_li3vhm.jpg"

[[recipes]]
id = "glace_flottante"
title = "Glace flottante ğŸ¦"
subtitle = "Tellement lÃ©gÃ¨re quâ€™elle flotte"
video = "https://www.facebook.com/chefclublightandfun/videos/369952870139677/"
recipecard = "http://res.cloudinary.com/dil9tlpjt/image/upload/v1521483111/030618_GLACE_FLOTTANTE_LF_bfoago.jpg"

[[recipes]]
id = "terrine_six"
title = "Terrine de lÃ©gumes 6 en 1 ğŸ†"
subtitle = "PrÃ©parez 6 jours de rÃ©gime avec 1 seule prÃ©paration :)"
video = "https://www.facebook.com/chefclublightandfun/videos/371993229935641/"
recipecard = "http://res.cloudinary.com/dil9tlpjt/image/upload/v1521642303/022718_TERRINE_LE%CC%81GUMES_LF_xxddbs.jpg"

[[recipes]]
id = "muffins_legumes"
title = "Muffins salÃ©s aux lÃ©gumes ! ğŸŒ¶ğŸ¥•"
subtitle = "Pour un apÃ©ro lÃ©ger :)"
video = "https://www.facebook.com/chefclublightandfun/videos/373152899819674/"
recipecard = "http://res.cloudinary.com/dil9tlpjt/image/upload/v1521884520/LF_MUFFINS_LEGUMES_hmwof7.png"

[[recipes]]
id = "croc_brocoli"
title = "Croc Brocoli ğŸ¥¦"
subtitle = "Au rÃ©gime Monsieur ! ou Madame :)"
video = "https://www.facebook.com/chefclublightandfun/videos/379997909135173/"
recipecard = "http://res.cloudinary.com/dil9tlpjt/image/upload/v1523287653/031218_CROC_BROC_LF_hboeq1.jpg"

[[recipes]]
id = "quiche_courgette"
title = "Quiche Courgette ğŸ¥’"
subtitle = "Un plat de rÃ©gime pour les quiches"
video = "https://www.facebook.com/chefclublightandfun/videos/388737968261167/"
recipecard = "http://res.cloudinary.com/dil9tlpjt/image/upload/v1525096574/041618_MUFFIN_COURGETTE_LF_spoq12.png"

[[recipes]]
id = "quiche_tomate"
title = "Quiche tomate farcie ğŸ…"
subtitle = "Elle est pas si quiche qu'elle en Ã  l'air ğŸ˜„"
video = "https://www.facebook.com/chefclublightandfun/videos/394852200983077/"
recipecard = "http://res.cloudinary.com/dil9tlpjt/image/upload/v1526656223/051018_TOMATE_FARCIE_QUICHE_CC_qddbqs.jpg"

[[recipes]]
id = "gaufre_accras"
title = "Gaufre accras de cabillaud ğŸŸ"
subtitle = "Une gaufre rÃ©gime au goÃ»t du large"
video = "https://www.facebook.com/chefclublightandfun/videos/406572129811084/"
recipecard = "http://res.cloudinary.com/dil9tlpjt/image/upload/v1529306666/032018_ACCRAS_GAUFFRE_LF_zu0qb9.png"

[[recipes]]
id = "sorbets_multicolores"
title = "Sorbets multicolores ğŸ¦"
subtitle = "Un rÃ©gime rafraÃ®chissant"
video = "https://www.facebook.com/chefclublightandfun/videos/409576276177336/"
recipecard = "http://res.cloudinary.com/dil9tlpjt/image/upload/v1529335906/051518_SORBETS_FRUITS_LF_nn46rg.png"

[[recipes]]
id = "apero_light"
title = "3 idÃ©es d'apÃ©ro light ğŸ¹"
subtitle = "Pour un Ã©tÃ© lÃ©ger "
video = "https://www.facebook.com/chefclublightandfun/videos/419341998534097/"
recipecard = "http://res.cloudinary.com/dil9tlpjt/image/upload/v1530286423/061518_APEROLIGHT_LF_mwh37a.png"

[[recipes]]
id = "tomates_fleurs"
title = "Tomates fleurs ğŸ…ğŸŒº"
subtitle = ""
video = "https://www.facebook.com/chefclublightandfun/videos/436401326828164/"
recipecard = "http://res.cloudinary.com/dil9tlpjt/image/upload/v1531993106/062618_TOMATES_FARCIES_ROSE_LF_swxscl.png"
