[[recipes]]
id = "poulet_arc_en_ciel"
title = "Poulet arc-en-ciel ğŸ“ğŸŒˆ"
subtitle = "Des couleurs et du goÃ»t ğŸ˜‹"
video = "https://www.facebook.com/chefclublightandfun/videos/353013945166903/"
recipecard = "http://res.cloudinary.com/dil9tlpjt/image/upload/v1521482471/012518_ROULE_POULET_LF_ezlfwv.jpg"

[[recipes]]
id = "quiche_patate_douce"
title = "La quiche patate douce ğŸ "
subtitle = "Un rÃ©gime Ã  la douce ğŸ˜Š"
video = "https://www.facebook.com/chefclublightandfun/videos/358379331297031/"
recipecard = "http://res.cloudinary.com/dil9tlpjt/image/upload/v1521482716/011018_QUICHE_PATATE_DOUCE_LF_ceej3f.jpg"

[[recipes]]
id = "mousse_chocolat_bi_gout"
title = "La mousse au chocolat bi-goÃ»t ğŸ«"
subtitle = "Onctueux et trÃ¨s peu calorique :)"
video = "https://www.facebook.com/chefclublightandfun/videos/365741530560811/"
recipecard = "http://res.cloudinary.com/dil9tlpjt/image/upload/v1521483006/022318_MOUSSE_CHOCOLAT_EAU_LF_ix9tgg.jpg"

[[recipes]]
id = "terrine_petits_legumes"
title = "Terrine aux petits lÃ©gumes ğŸ¥¦ğŸ¥•ğŸ†"
subtitle = "Aussi lÃ©gÃ¨re que colorÃ©e"
video = "https://www.facebook.com/chefclublightandfun/videos/366697307131900/"
recipecard = "http://res.cloudinary.com/dil9tlpjt/image/upload/v1521483050/020618_TERRINE_TROIS_LEGUMES_LF_fsf7vz.jpg"

[[recipes]]
id = "chou_fleur_margherita"
title = "Chou-fleur faÃ§on margherita ğŸ•"
subtitle = "Tous les bons cÃ´tÃ©s de la pizza en plus lÃ©ger :)"
video = "https://www.facebook.com/chefclublightandfun/videos/369213040213660/"
recipecard = "http://res.cloudinary.com/dil9tlpjt/image/upload/v1521483076/011118_PIZZA_CHOUFLEUR_LF_li3vhm.jpg"

[[recipes]]
id = "glace_flottante"
title = "Glace flottante ğŸ¦"
subtitle = "Tellement lÃ©gÃ¨re quâ€™elle flotte"
video = "https://www.facebook.com/chefclublightandfun/videos/369952870139677/"
recipecard = "http://res.cloudinary.com/dil9tlpjt/image/upload/v1521483111/030618_GLACE_FLOTTANTE_LF_bfoago.jpg"

[[recipes]]
id = "terrine_six"
title = "Terrine de lÃ©gumes 6 en 1 ğŸ†"
subtitle = "PrÃ©parez 6 jours de rÃ©gime avec 1 seule prÃ©paration :)"
video = "https://www.facebook.com/chefclublightandfun/videos/371993229935641/"
recipecard = "http://res.cloudinary.com/dil9tlpjt/image/upload/v1521642303/022718_TERRINE_LE%CC%81GUMES_LF_xxddbs.jpg"
